export const ADD_TO_CART = 'addToCart'
export const ADD_COUNTER = 'addCounter'
export const CHECK_CLICK = 'checkClick'
export const DELETE_INFO = 'delete_info'
export const REDUCE_COUNTER = 'reduceCounter'
